jobs:
  autograding:
    name: autograding
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wadefagen/autograding@v1
      with:
        path: mp1/
        test_suite: autograding
    timeout-minutes: 5
  start:
    name: start
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wadefagen/autograding@v1
      with:
        path: mp1/
        test_suite: start
    timeout-minutes: 5
name: mp1 autograding
'on':
  push:
    paths: mp1/**
