jobs:
  autograding:
    name: autograding
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wadefagen/autograding@v2
      with:
        path: mp4/
        test_suite: autograding
    timeout-minutes: 5
  valgrind:
    name: valgrind
    needs:
    - autograding
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install valgrind
      run: sudo apt install -y valgrind
    - uses: wadefagen/autograding@v2
      with:
        path: mp4/
        test_suite: valgrind
    timeout-minutes: 5
name: mp4 autograding
'on':
  workflow_dispatch: ''
